/**
 * `WebhookEndpointStore` — persistence for `webhook_endpoints` (migration
 * 022, `src/db/migrate.ts`; HT-68, specs/plugins/substrate-v1.md §5 —
 * "module" below always means an out-of-process Helpthread extension,
 * never the legal "plugin exception" phrase CHARTER.md §7 uses).
 *
 * Mirrors `src/store/mailbox-tokens.ts`'s encrypt-at-rest shape: the
 * caller supplies a PLAINTEXT secret, this store encrypts it with
 * `src/store/token-crypto.ts`'s existing AES-256-GCM envelope before it
 * ever reaches the database, and only {@link WebhookEndpointStore.getSecret}
 * decrypts it back — the one caller with a legitimate need (wave 3's
 * delivery handler, signing `X-Helpthread-Signature`, spec §5: "signing
 * needs the plaintext back"). No new crypto code — a second caller of the
 * module `mailbox-tokens.ts` already depends on.
 *
 * ## Secret generation is NOT this module's job
 *
 * Spec §5 says the secret is "server-generated" — but exactly like
 * `src/store/assistants.ts`'s token-hashing boundary, generating it is
 * wave 2/3 admin-route work (`POST /api/v1/webhooks`) this ticket's
 * boundary excludes. {@link WebhookEndpointStore.create} takes an
 * already-generated plaintext `secret` and only handles encrypting it at
 * rest.
 *
 * ## `create` is idempotent on `url` (HT-119 review fix, migration 031)
 *
 * `url` now carries a unique index specifically so two callers racing to
 * register the SAME url (the module installer's `bootstrap_pending` step,
 * on a concurrent retry or a genuine two-worker race) cannot both leave a
 * live, independently-delivered-to endpoint behind — see migration 031's
 * doc comment. {@link WebhookEndpointStore.create} therefore uses the same
 * `INSERT ... ON CONFLICT DO NOTHING` / fallback-`SELECT` shape
 * `ModuleInstallStore.create` already uses for `idempotency_key`: a second
 * `create` for a url that already has a row is coalesced onto that SAME
 * row (returning ITS actual secret, decrypted — never the caller's
 * freshly-supplied one, which the conflicting row may not actually hold)
 * rather than throwing a raw unique-violation or silently duplicating.
 *
 * ## Auto-disable (spec §5, spec §9 decision 2: 20, admin re-enable)
 *
 * {@link WebhookEndpointStore.recordDeliveryFailure} increments
 * `consecutive_failures` and, ONLY when the endpoint is currently `'active'`
 * (never overriding an operator's deliberate `'disabled'`), flips it to
 * `'auto_disabled'` the moment the counter reaches {@link
 * WEBHOOK_AUTO_DISABLE_THRESHOLD}. {@link
 * WebhookEndpointStore.recordDeliverySuccess} resets the counter to zero
 * but does NOT touch `status` — re-enabling a disabled/auto_disabled
 * endpoint is a deliberate admin action ({@link WebhookEndpointStore.patch}
 * with `status: 'active'`), never an implicit side effect of one stray
 * success. `patch`'s own `status: 'active'` branch resets the counter to
 * zero for the same reason `recordDeliverySuccess` does — a fresh
 * re-enable should not inherit a near-threshold failure count from before
 * the operator intervened.
 */

import type { Db, SqlValue } from '../db/client.js'
import { decrypt, encrypt } from './token-crypto.js'

/** A webhook endpoint's lifecycle status (spec §5). `active` receives deliveries; `disabled` is an operator's own choice; `auto_disabled` is written only by {@link WebhookEndpointStore.recordDeliveryFailure} at the failure threshold — kept distinct from `disabled` so an auto-disable can never masquerade as a manual one. */
export type WebhookEndpointStatus = 'active' | 'disabled' | 'auto_disabled'

/** Consecutive delivery failures at which an `active` endpoint auto-disables (spec §9 decision 2). */
export const WEBHOOK_AUTO_DISABLE_THRESHOLD = 20

/** Input to {@link WebhookEndpointStore.create}. */
export interface NewWebhookEndpoint {
  /** `https://` only — enforced by both the schema CHECK (migration 022) and, eventually, wave 3's SSRF-pinning delivery handler (spec §5). */
  url: string
  /** Plaintext secret — server-generated by the caller (wave 2/3), encrypted by this store before persist. Never stored or logged in plaintext. */
  secret: string
  /** A subset of spec §4's event-type list, or `[]` (interpreted by the API layer as "all" — this store takes no position, spec §5's "or all"). Persisted verbatim, the same `conversations.tags` convention. */
  events: string[]
  /** The slug of the module that registered this endpoint, or omitted/`null` for an operator-registered one not tied to any module (spec §1's additive-forward rule). */
  module?: string | null
  /** Initial status — defaults to the schema default `'active'`. The installer (`../modules/install/installer.ts`'s `stepBootstrapPending`) passes `'disabled'` explicitly to create the row BEFORE it has proven itself, promoting to `'active'` only after winning its own fenced CAS (module doc's "candidate-then-cutover" discipline). */
  status?: 'active' | 'disabled'
}

/** A webhook endpoint as read back from storage — camelCase, timestamps as `Date`. Never carries the secret (see {@link WebhookEndpointStore.getSecret} for the one path that reaches it, decrypted). */
export interface StoredWebhookEndpoint {
  id: string
  url: string
  events: string[]
  module: string | null
  status: WebhookEndpointStatus
  consecutiveFailures: number
  createdAt: Date
  updatedAt: Date
}

/** {@link WebhookEndpointStore.create}'s return shape: the stored fields plus the plaintext `secret`, returned exactly once (spec §5: "returned once") — never re-derivable after this call, since only the ciphertext persists. */
export interface CreatedWebhookEndpoint extends StoredWebhookEndpoint {
  secret: string
}

/** Fields {@link WebhookEndpointStore.patch} may change (spec §5's admin API: `PATCH /api/v1/webhooks/{id}`). `status` here is deliberately narrower than {@link WebhookEndpointStatus} — `'auto_disabled'` is engine-written only (module doc), never admin-settable directly; an admin re-enables by setting `'active'`. */
export interface WebhookEndpointPatch {
  url?: string
  events?: string[]
  module?: string | null
  status?: 'active' | 'disabled'
}

/** Persistence operations for `webhook_endpoints`. See the module doc for the encrypt-at-rest and auto-disable contracts. */
export interface WebhookEndpointStore {
  /** Insert a new endpoint, `status: 'active'` (the schema default), encrypting `input.secret` before persist. Returns the created row WITH the plaintext secret (spec §5: shown once). */
  create(input: NewWebhookEndpoint): Promise<CreatedWebhookEndpoint>

  /** List every webhook endpoint, ordered by `created_at` — the roster `GET /api/v1/webhooks` (spec §5) serves. Never includes the secret. */
  list(): Promise<StoredWebhookEndpoint[]>

  /** Apply `patch` to endpoint `id`. A `status: 'active'` transition also resets `consecutive_failures` to `0` (module doc). Returns the updated record, or `null` if `id` doesn't exist. */
  patch(id: string, patch: WebhookEndpointPatch): Promise<StoredWebhookEndpoint | null>

  /** Hard delete endpoint `id`. Returns `true` if a row was deleted, `false` if `id` didn't exist. */
  delete(id: string): Promise<boolean>

  /**
   * Decrypt and return endpoint `id`'s secret — the one path that reaches
   * plaintext after creation (wave 3's delivery handler, signing the HMAC
   * per spec §5). `null` if `id` doesn't exist. Throws if decryption fails
   * (see `token-crypto.ts`'s `decrypt`) rather than returning a silently
   * wrong value.
   */
  getSecret(id: string): Promise<string | null>

  /**
   * Record one failed delivery attempt (wave 3's delivery handler, after
   * exhausting the queue's retry policy — spec §5: "dead-letters against
   * the endpoint"): increments `consecutive_failures`, and — only if the
   * endpoint is currently `'active'` — flips it to `'auto_disabled'` once
   * the counter reaches {@link WEBHOOK_AUTO_DISABLE_THRESHOLD}, in the SAME
   * statement (no separate read-then-write race). Returns the updated
   * record, or `null` if `id` doesn't exist.
   */
  recordDeliveryFailure(id: string): Promise<StoredWebhookEndpoint | null>

  /**
   * Record one successful delivery: resets `consecutive_failures` to `0`.
   * Does NOT change `status` (module doc). Returns the updated record, or
   * `null` if `id` doesn't exist.
   */
  recordDeliverySuccess(id: string): Promise<StoredWebhookEndpoint | null>
}

/** Raw `webhook_endpoints` row shape, before mapping to {@link StoredWebhookEndpoint}. */
interface WebhookEndpointRow {
  id: string
  url: string
  secret_ciphertext: Uint8Array
  events: unknown
  module: string | null
  status: string
  consecutive_failures: number
  created_at: Date | string
  updated_at: Date | string
}

const WEBHOOK_ENDPOINT_COLUMNS =
  'id, url, secret_ciphertext, events, module, status, consecutive_failures, created_at, updated_at'

function toDate(value: Date | string): Date {
  return value instanceof Date ? value : new Date(value)
}

function toStoredWebhookEndpoint(row: WebhookEndpointRow): StoredWebhookEndpoint {
  return {
    id: row.id,
    url: row.url,
    // Cast, not parsed — same reasoning as conversations.ts's `tags`: this
    // codebase is the only writer (always a JSON string array), and jsonb
    // arrives already decoded.
    events: row.events as string[],
    module: row.module,
    status: row.status as WebhookEndpointStatus,
    consecutiveFailures: row.consecutive_failures,
    createdAt: toDate(row.created_at),
    updatedAt: toDate(row.updated_at),
  }
}

/**
 * Create a {@link WebhookEndpointStore} backed by `db`, encrypting/
 * decrypting secrets with `encryptionKey`. `encryptionKey` must be a
 * 32-byte `Buffer` — decode it once at the composition root via
 * `token-crypto.ts`'s `decodeEncryptionKey` and pass the result in here,
 * the same convention `createMailboxTokenStore` uses (and, in a real
 * deployment, the SAME key — this module reuses `mailbox-tokens.ts`'s
 * crypto primitives, not a second key hierarchy).
 */
export function createWebhookEndpointStore(db: Db, encryptionKey: Buffer): WebhookEndpointStore {
  return {
    async create(input) {
      const secretCiphertext = encrypt(input.secret, encryptionKey)
      const inserted = await db.query<WebhookEndpointRow>(
        `INSERT INTO webhook_endpoints (url, secret_ciphertext, events, module, status)
         VALUES ($1, $2, $3::jsonb, $4, $5)
         ON CONFLICT (url) DO NOTHING
         RETURNING ${WEBHOOK_ENDPOINT_COLUMNS}`,
        [
          input.url,
          secretCiphertext,
          JSON.stringify(input.events),
          input.module ?? null,
          input.status ?? 'active',
        ],
      )
      if (inserted.length > 0) {
        return { ...toStoredWebhookEndpoint(inserted[0]), secret: input.secret }
      }

      // Conflict on url — module doc's "create is idempotent on url".
      const existing = await db.query<WebhookEndpointRow>(
        `SELECT ${WEBHOOK_ENDPOINT_COLUMNS} FROM webhook_endpoints WHERE url = $1`,
        [input.url],
      )
      const row = existing[0]
      if (row === undefined) {
        throw new Error(
          `webhook-endpoints: create() conflicted on url ${input.url} but no existing row was found`,
        )
      }
      return {
        ...toStoredWebhookEndpoint(row),
        secret: decrypt(row.secret_ciphertext, encryptionKey),
      }
    },

    async list() {
      const rows = await db.query<WebhookEndpointRow>(
        `SELECT ${WEBHOOK_ENDPOINT_COLUMNS} FROM webhook_endpoints ORDER BY created_at`,
      )
      return rows.map(toStoredWebhookEndpoint)
    },

    async patch(id, patch) {
      const sets: string[] = []
      const params: SqlValue[] = []
      if (patch.url !== undefined) {
        params.push(patch.url)
        sets.push(`url = $${params.length}`)
      }
      if (patch.events !== undefined) {
        params.push(JSON.stringify(patch.events))
        sets.push(`events = $${params.length}::jsonb`)
      }
      if (patch.module !== undefined) {
        params.push(patch.module)
        sets.push(`module = $${params.length}`)
      }
      if (patch.status !== undefined) {
        params.push(patch.status)
        sets.push(`status = $${params.length}`)
        if (patch.status === 'active') {
          // Re-enable resets the failure count — module doc.
          sets.push('consecutive_failures = 0')
        }
      }
      if (sets.length === 0) {
        const rows = await db.query<WebhookEndpointRow>(
          `SELECT ${WEBHOOK_ENDPOINT_COLUMNS} FROM webhook_endpoints WHERE id = $1`,
          [id],
        )
        const row = rows[0]
        return row === undefined ? null : toStoredWebhookEndpoint(row)
      }
      params.push(id)
      const rows = await db.query<WebhookEndpointRow>(
        `UPDATE webhook_endpoints SET ${sets.join(', ')}, updated_at = now()
         WHERE id = $${params.length}
         RETURNING ${WEBHOOK_ENDPOINT_COLUMNS}`,
        params,
      )
      const row = rows[0]
      return row === undefined ? null : toStoredWebhookEndpoint(row)
    },

    async delete(id) {
      const rows = await db.query<{ id: string }>(
        'DELETE FROM webhook_endpoints WHERE id = $1 RETURNING id',
        [id],
      )
      return rows.length === 1
    },

    async getSecret(id) {
      const rows = await db.query<{ secret_ciphertext: Uint8Array }>(
        'SELECT secret_ciphertext FROM webhook_endpoints WHERE id = $1',
        [id],
      )
      const row = rows[0]
      return row === undefined ? null : decrypt(row.secret_ciphertext, encryptionKey)
    },

    async recordDeliveryFailure(id) {
      const rows = await db.query<WebhookEndpointRow>(
        `UPDATE webhook_endpoints
         SET consecutive_failures = consecutive_failures + 1,
             status = CASE
               WHEN status = 'active' AND consecutive_failures + 1 >= $2 THEN 'auto_disabled'
               ELSE status
             END,
             updated_at = now()
         WHERE id = $1
         RETURNING ${WEBHOOK_ENDPOINT_COLUMNS}`,
        [id, WEBHOOK_AUTO_DISABLE_THRESHOLD],
      )
      const row = rows[0]
      return row === undefined ? null : toStoredWebhookEndpoint(row)
    },

    async recordDeliverySuccess(id) {
      const rows = await db.query<WebhookEndpointRow>(
        `UPDATE webhook_endpoints
         SET consecutive_failures = 0, updated_at = now()
         WHERE id = $1
         RETURNING ${WEBHOOK_ENDPOINT_COLUMNS}`,
        [id],
      )
      const row = rows[0]
      return row === undefined ? null : toStoredWebhookEndpoint(row)
    },
  }
}
